### ISSUE TITLE
Cannot input multiple files 

### ISSUE THREAD

**Issue by InderParmar** [Fahad-Ali-Khan-ca/EnglishFormatter#1]
Hi Fahad, I reviewed your code and found out that you cannot input multiple file names in your Format, Summarize, Paraphrase functions. This is a requirement of release 0.1 so I suggest that you should modify your code to let multiple files input before you submit the code for submissions

Regards,
Inderpreet Singh

**Comment by Fahad-Ali-Khan-ca** [comment]
OMG! thanks alot I would've lost marks if I missed it. Thanks for pointing it out. I will amend it in future commits
