### ISSUE TITLE
Use of <conio.h>:

### ISSUE THREAD

**Issue by InderParmar** [Fahad-Ali-Khan-ca/EnglishFormatter#2]
Hi Fahad, the header <conio.h> is non-standard and specific to older compilers like Turbo C++ on DOS. It may not work on modern compilers or platforms like Linux or macOS. You can replace functionality such as getch() with modern alternatives, such as using <iostream> for input handling. I would suggest replace deprecated <conio.h> with modern input handling methods.

Thanks,
Regards,
Inderpreet Singh

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi Inder, I deliberately chose conio.h because it designed the menu the way I wanted. I must admit I didn't think about portability to other systems. I plan to make a part in my readme file that instructs users to download and compile conio.h
