### ISSUE TITLE
API key as a class member without security handling:

### ISSUE THREAD

**Issue by InderParmar** [Fahad-Ali-Khan-ca/EnglishFormatter#3]
Storing the API key as a public class member (std::string Api_Key;) is not secure. Sensitive data, like API keys, should be securely handled and not exposed in plain text. I would suggest secure API key storage and handling to prevent exposure

Regards Inderpreet Singh

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi Inder, thanks for pointing it out I meant to change it but forgot about it.
