### ISSUE TITLE
Add --token-usage Flag to Display Token Usage Information

### ISSUE THREAD

**Issue by InderParmar** [Fahad-Ali-Khan-ca/EnglishFormatter#5]
I would like to propose a new feature that adds a `--token-usage` or `-t` command-line flag to the tool. This flag would output information about token usage to `stderr`, helping users better understand how many tokens were used during both the prompt and the completion.

Feature Details: 
When the `--token-usage` flag is set, the tool should:
 *Output the number of tokens used in the **prompt** (e.g., `prompt_tokens`).
 *Output the number of tokens used in the **completion** (e.g., `completion_tokens`).
  *Output the **total tokens** used (i.e., `completion_tokens + prompt_tokens`).
  
- The token usage information will be extracted from the response provided by the LLM provider (e.g., OpenAI, Groq, etc.).

If the flag is set, the tool will display the following information to `stderr`:
```
Prompt Tokens: 57
Completion Tokens: 17
Total Tokens: 74
```

Why This Feature is Useful:

- Knowing how many tokens are used is important for both cost management (since most LLM providers charge based on the number of tokens) and for ensuring that the request fits within the model's context length.
- This feature will allow users to debug and optimize their usage of LLMs, ensuring they stay within token limits and avoid potential errors caused by exceeding the token budget.
Proposed Approach:

1. Add support for the `--token-usage` or `-t` flag in the command-line options.
2. Extract token usage information from the LLM response (e.g., `usage.prompt_tokens`, `usage.completion_tokens`, `usage.total_tokens`).
3. Output the token information to `stderr` when the flag is enabled.

Let me know if you approve this feature request, and I would be happy to work on it!

**Comment by Fahad-Ali-Khan-ca** [comment]
Nicely done
